### ISSUE TITLE
 Consider supporting inheritance or removing the sealed requirement? 

### ISSUE THREAD

**Issue by CyborTronik** [EamonNerbonne/ValueUtils#37]
Reopening https://github.com/EamonNerbonne/ValueUtils/issues/1
as this kinda blocks the usage of the library

**Comment by EamonNerbonne** [comment]
Can you explain why this blocks your usage?

**Comment by EamonNerbonne** [comment]
To be clear; you can use inheritance like `sealed class MyValueObject : ValueObject<MyValueObject>` just fine; and it's a best practice to seal classes that aren't open to inheritance anyhow.

The issue is that equality is intrinsically not well suited to inheritance, so a fix is tricky.

Say you have `class MySubClass : MyValueObject { public int Tricky; }` - well, what's supposed to happen then?

The `IEquatable<T>` interface is still going to be `IEquatable<MyValueObject>`, even for MySubClass  instances.

So what would the expected behavior be when you do something like `myValueObjectInstance.Equals(mySubClassInstance)`? Is that false because they're different types?  Or does it just ignore the field `Tricky`?

**Comment by EamonNerbonne** [comment]
Thanks for the feedback, by the way!

**Comment by EamonNerbonne** [comment]
Actually, to keep this a little more together; I'm going to move my comments to #1 and reopen that .

**Comment by EamonNerbonne** [comment]
closed because #1 is reopened as requested.
