### ISSUE TITLE
Dot Net Core support

### ISSUE THREAD

**Issue by mcintyre321** [EamonNerbonne/ValueUtils#5]
Would be nice to have this in core!

**Comment by EamonNerbonne** [comment]
Yeah, and I'm certainly going to port it - however, in the name of expediency, I've waited for reasonable tooling support to do so.  I've just downloaded VS2017RC, so I'll give conversion a shot.

My plan is to convert this at the latest a month or two after RTM; faster if it turns out to be easy!

If you have any tips/tricks/pointers/ideas I'm all ears!  And of course PRs (even non-compiling proof-of-concept ones) are definitely welcome, if you happen to know how to do this and feel particularly magnanimous with your time!

**Comment by EamonNerbonne** [comment]
@mcintyre321 The .net core conversion is done; it's [version 1.4.0 on nuget](https://www.nuget.org/packages/ValueUtils/1.4.0).

**Comment by mcintyre321** [comment]
Cool, thanks!
